;
; Prak3_assembler.asm
;
; Created: 24.10.2019 17:24:24
; Author : bh8332s
;

.include "m8def.inc"

.def ledOutput = r16

.org 0x000
	jmp initialize
.org INT0addr   ;INT0_vect
    jmp somewhere
.org INT1addr   ;INT1_vect
    jmp somewhere

somewhere:
    rjmp somewhere


initialize:
    ldi r16, LOW(RAMEND)
    out SPL, r16
    ldi 16, HIGH(RAMEND)
    out SPH, r16

    ldi ledOutput, 0b00000011 ;LED 0,1 als Ausgang
    out DDRB, ledOutput
    ldi r16, 0x00
    out DDRD, r16

    ldi r16, 0xFF
    out PORTD, r16              ;PullUps fuer Taster

start:
    rjmp start

checkTaster1:   ;PD1
    out r16, PIND
    OR r16, 0b00000010
    cp r16, PIND
    BRNE ;NOTEQUAL
    ;EQUAL

checkTaster2:   ;PD2
    out r16, PIND
    OR r16, 0b00000100
    cp r16, PIND
    BRNE ;NOTEQUAL
    ;EQUAL


offLED0:
    ANDI PORTB, 0b11111110
    ret

offLED1:
    ANDI PORTB, 0b11111101
    ret

toggleLED0:
    eor PORTB, 0b00000001
    ret

toggleLED1:
    eor PORTB, 0b00000010
    ret

delay_200ms:
; Generated by delay loop calculator
; at http://www.bretmulvey.com/avrdelay.html
;
; Delay 200 000 cycles
; 200ms at 1 MHz

    ldi  r18, 2
    ldi  r19, 4
    ldi  r20, 187
L1: dec  r20
    brne L1
    dec  r19
    brne L1
    dec  r18
    brne L1
    nop
	ret